# coding: utf-8

"""
    Xero Payroll NZ

    This is the Xero Payroll API for orgs in the NZ region.  # noqa: E501

    Contact: api@xero.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401

from xero_python.models import BaseModel


class EmployeeWorkingPatternWithWorkingWeeksObject(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "pagination": "Pagination",
        "problem": "Problem",
        "payee_working_pattern": "EmployeeWorkingPatternWithWorkingWeeks",
    }

    attribute_map = {
        "pagination": "pagination",
        "problem": "problem",
        "payee_working_pattern": "payeeWorkingPattern",
    }

    def __init__(
        self, pagination=None, problem=None, payee_working_pattern=None
    ):  # noqa: E501
        """EmployeeWorkingPatternWithWorkingWeeksObject - a model defined in OpenAPI"""  # noqa: E501

        self._pagination = None
        self._problem = None
        self._payee_working_pattern = None
        self.discriminator = None

        if pagination is not None:
            self.pagination = pagination
        if problem is not None:
            self.problem = problem
        if payee_working_pattern is not None:
            self.payee_working_pattern = payee_working_pattern

    @property
    def pagination(self):
        """Gets the pagination of this EmployeeWorkingPatternWithWorkingWeeksObject.  # noqa: E501


        :return: The pagination of this EmployeeWorkingPatternWithWorkingWeeksObject.  # noqa: E501
        :rtype: Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination):
        """Sets the pagination of this EmployeeWorkingPatternWithWorkingWeeksObject.


        :param pagination: The pagination of this EmployeeWorkingPatternWithWorkingWeeksObject.  # noqa: E501
        :type: Pagination
        """

        self._pagination = pagination

    @property
    def problem(self):
        """Gets the problem of this EmployeeWorkingPatternWithWorkingWeeksObject.  # noqa: E501


        :return: The problem of this EmployeeWorkingPatternWithWorkingWeeksObject.  # noqa: E501
        :rtype: Problem
        """
        return self._problem

    @problem.setter
    def problem(self, problem):
        """Sets the problem of this EmployeeWorkingPatternWithWorkingWeeksObject.


        :param problem: The problem of this EmployeeWorkingPatternWithWorkingWeeksObject.  # noqa: E501
        :type: Problem
        """

        self._problem = problem

    @property
    def payee_working_pattern(self):
        """Gets the payee_working_pattern of this EmployeeWorkingPatternWithWorkingWeeksObject.  # noqa: E501


        :return: The payee_working_pattern of this EmployeeWorkingPatternWithWorkingWeeksObject.  # noqa: E501
        :rtype: EmployeeWorkingPatternWithWorkingWeeks
        """
        return self._payee_working_pattern

    @payee_working_pattern.setter
    def payee_working_pattern(self, payee_working_pattern):
        """Sets the payee_working_pattern of this EmployeeWorkingPatternWithWorkingWeeksObject.


        :param payee_working_pattern: The payee_working_pattern of this EmployeeWorkingPatternWithWorkingWeeksObject.  # noqa: E501
        :type: EmployeeWorkingPatternWithWorkingWeeks
        """

        self._payee_working_pattern = payee_working_pattern
