# coding: utf-8

"""
    Xero AppStore API

    These endpoints are for Xero Partners to interact with the App Store Billing platform  # noqa: E501

    Contact: api@xero.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401

from xero_python.models import BaseModel


class CreateUsageRecord(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {"quantity": "int", "timestamp": "datetime"}

    attribute_map = {"quantity": "quantity", "timestamp": "timestamp"}

    def __init__(self, quantity=None, timestamp=None):  # noqa: E501
        """CreateUsageRecord - a model defined in OpenAPI"""  # noqa: E501

        self._quantity = None
        self._timestamp = None
        self.discriminator = None

        self.quantity = quantity
        self.timestamp = timestamp

    @property
    def quantity(self):
        """Gets the quantity of this CreateUsageRecord.  # noqa: E501

        The initial quantity for the usage record. Must be a whole number that is greater than or equal to 0  # noqa: E501

        :return: The quantity of this CreateUsageRecord.  # noqa: E501
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this CreateUsageRecord.

        The initial quantity for the usage record. Must be a whole number that is greater than or equal to 0  # noqa: E501

        :param quantity: The quantity of this CreateUsageRecord.  # noqa: E501
        :type: int
        """
        if quantity is None:
            raise ValueError(
                "Invalid value for `quantity`, must not be `None`"
            )  # noqa: E501

        self._quantity = quantity

    @property
    def timestamp(self):
        """Gets the timestamp of this CreateUsageRecord.  # noqa: E501

        DateTime in UTC of when the the product was consumed/used  # noqa: E501

        :return: The timestamp of this CreateUsageRecord.  # noqa: E501
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this CreateUsageRecord.

        DateTime in UTC of when the the product was consumed/used  # noqa: E501

        :param timestamp: The timestamp of this CreateUsageRecord.  # noqa: E501
        :type: datetime
        """
        if timestamp is None:
            raise ValueError(
                "Invalid value for `timestamp`, must not be `None`"
            )  # noqa: E501

        self._timestamp = timestamp
