# coding: utf-8

# flake8: noqa
"""
    Xero Assets API

    The Assets API exposes fixed asset related functions of the Xero Accounting application and can be used for a variety of purposes such as creating assets, retrieving asset valuations etc.  # noqa: E501

    Contact: api@xero.com
    Generated by: https://openapi-generator.tech
"""


# import models into model package
from xero.assets.models.asset import Asset
from xero.assets.models.asset_status import AssetStatus
from xero.assets.models.asset_status_query_param import AssetStatusQueryParam
from xero.assets.models.asset_type import AssetType
from xero.assets.models.assets import Assets
from xero.assets.models.book_depreciation_detail import BookDepreciationDetail
from xero.assets.models.book_depreciation_setting import BookDepreciationSetting
from xero.assets.models.error import Error
from xero.assets.models.field_validation_errors_element import (
    FieldValidationErrorsElement,
)
from xero.assets.models.pagination import Pagination
from xero.assets.models.resource_validation_errors_element import (
    ResourceValidationErrorsElement,
)
from xero.assets.models.setting import Setting
