# coding: utf-8

"""
    Xero Finance API

    The Finance API is a collection of endpoints which customers can use in the course of a loan application, which may assist lenders to gain the confidence they need to provide capital.  # noqa: E501

    Contact: api@xero.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401

from xero_python.models import BaseModel


class Problem(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "type": "ProblemType",
        "title": "str",
        "status": "int",
        "detail": "str",
    }

    attribute_map = {
        "type": "type",
        "title": "title",
        "status": "status",
        "detail": "detail",
    }

    def __init__(self, type=None, title=None, status=None, detail=None):  # noqa: E501
        """Problem - a model defined in OpenAPI"""  # noqa: E501

        self._type = None
        self._title = None
        self._status = None
        self._detail = None
        self.discriminator = None

        if type is not None:
            self.type = type
        if title is not None:
            self.title = title
        if status is not None:
            self.status = status
        if detail is not None:
            self.detail = detail

    @property
    def type(self):
        """Gets the type of this Problem.  # noqa: E501


        :return: The type of this Problem.  # noqa: E501
        :rtype: ProblemType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Problem.


        :param type: The type of this Problem.  # noqa: E501
        :type: ProblemType
        """

        self._type = type

    @property
    def title(self):
        """Gets the title of this Problem.  # noqa: E501


        :return: The title of this Problem.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Problem.


        :param title: The title of this Problem.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def status(self):
        """Gets the status of this Problem.  # noqa: E501


        :return: The status of this Problem.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Problem.


        :param status: The status of this Problem.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def detail(self):
        """Gets the detail of this Problem.  # noqa: E501


        :return: The detail of this Problem.  # noqa: E501
        :rtype: str
        """
        return self._detail

    @detail.setter
    def detail(self, detail):
        """Sets the detail of this Problem.


        :param detail: The detail of this Problem.  # noqa: E501
        :type: str
        """

        self._detail = detail
